apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.51.217
  clusterIPs:
  - 10.110.51.217
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 32400
    protocol: TCP
    targetPort: 32400
    name: plex
  - port: 32400
    protocol: UDP
    targetPort: 32400
    name: plex-udp
  - port: 32469
    protocol: TCP
    targetPort: 32469
    name: plex2    
  - port: 32469
    protocol: UDP
    targetPort: 32469
    name: plex2-udp
  - port: 5353
    protocol: UDP
    targetPort: 5353
    name: plex3-udp
  - port: 1900
    protocol: UDP
    targetPort: 1900
    name: plex4-udp      
  selector:
    app: plex
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.17.50.101
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
spec:
  serviceName: "plex"
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: linuxserver/plex
        imagePullPolicy: Always
        ports:
        - containerPort: 32400
          name: plex
        - containerPort: 32400
          name: plex-udp
          protocol: UDP
        - containerPort: 32469
          name: plex2
        - containerPort: 32469
          name: plex2-udp
          protocol: UDP
        - containerPort: 5353
          name: plex3-udp
          protocol: UDP
        - containerPort: 1900
          name: plex4-udp
          protocol: UDP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: VERSION
          value: "latest"
        - name: ADVERTISE_IP 
          value: "http://172.17.50.101:32400"
        - name: PLEX_CLAIM
          value: 
        volumeMounts:
        - mountPath: /nfs
          name: tv
        - mountPath: /config
          name: plexconfig
      volumes:
      - name: tv
        nfs:
          path: /mnt/user/tv
          server: 172.16.2.10
#      - name: config
#        nfs:
#          path: /mnt/user/appdata/k8s-plex
#          server: 172.16.2.10
  volumeClaimTemplates:
  - metadata:
      name: plexconfig
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
