apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: plex
    spec:
      nodeSelector:
        fileserv: "true"
      containers:
      - name: plex
        image: linuxserver/plex
        imagePullPolicy: Always
        ports:
        - containerPort: 32400
          name: plex
        - containerPort: 32400
          name: plex-udp
          protocol: UDP
        - containerPort: 32469
          name: plex2
        - containerPort: 32469
          name: plex2-udp
          protocol: UDP
        - containerPort: 5353
          name: plex3-udp
          protocol: UDP
        - containerPort: 1900
          name: plex4-udp
          protocol: UDP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: VERSION
          value: "latest"
        volumeMounts:
        - name: nfs
          mountPath: /nfs
      volumes:
      - name: nfs
        nfs:
          path: /mnt/user/tv
          server: 172.16.2.10
